{% set name = "atpbar" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b642f9ff2fe0b0ee72f347aea0c6a9a6bda249947c704a36e5a9f0c519f100b2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - hatchling
    - hatch-regex-commit
  run:
    - python
  run_constrained:
    - jupyter
    - ipywidgets
    - widgetsnbextension

test:
  imports:
    - atpbar

about:
  home: https://github.com/alphatwirl/atpbar
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Progress bars for threading and multiprocessing tasks on terminal and Jupyter Notebook
  description: |
    atpbar can display multiple progress bars simultaneously growing
    to show the progresses of iterations of loops in threading or
    multiprocessing tasks on terminal and Jupyter Notebook.
  dev_url: https://github.com/alphatwirl/atpbar
  doc_url: https://github.com/alphatwirl/atpbar#atpbar

extra:
  recipe-maintainers:
    - TaiSakuma
