{% set name = "atpbar" %}
{% set version = "2.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 26051d9695a5c4576af8a5713c8976ddb91d458c8f4eff6f24fe78b7b7d9fa5f
build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-regex-commit
  run:
    - python >={{ python_min }}
  run_constrained:
    - jupyter
    - ipywidgets
    - widgetsnbextension

test:
  requires:
    - python {{ python_min }}
  imports:
    - atpbar

about:
  home: https://github.com/alphatwirl/atpbar
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Progress bars for threading and multiprocessing tasks on terminal and Jupyter Notebook
  description: |
    atpbar can display multiple progress bars simultaneously growing
    to show the progresses of iterations of loops in threading or
    multiprocessing tasks on terminal and Jupyter Notebook.
  dev_url: https://github.com/alphatwirl/atpbar
  doc_url: https://github.com/alphatwirl/atpbar#atpbar

extra:
  recipe-maintainers:
    - TaiSakuma
